version: '2'
services:
  webapp:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www-data:/www-data
  monitoring:
    image: arpinum/hello-monitoring
    environment:
      URL: http://webapp
      EXPECTED_RESPONSE: "ok"
